import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header/Header";
import Footer from "@/components/common/footer/Footer";
import SocialLinks from "@/components/SocialLinks";
import ClientLayout from "@/components/common/ClientLayout"; // 👈 New file

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tekbooster",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <ClientLayout>{children}</ClientLayout> {/* 👈 Wrap children in client-side animation */}
        <SocialLinks />
        <Footer />
      </body>
    </html>
  );
}